### ISSUE TITLE
💗 those screenshots!  Maybe add PySimpleGUI and requests to your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [polymathrobotics/caladan_examples#20]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

It's a "readme thing"

# Current Behavior

![image](https://user-images.githubusercontent.com/46163555/181516861-2f5e5f6f-b07c-4dbe-bc98-3a744d031e9f.png)

# Failure Information (for bugs)

Both PySimpleGUI and requests are also required

## Steps to Reproduce

Go here: https://github.com/polymathrobotics/caladan_examples

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

N/A I think

## Failure Logs

No logs... it's a "readme thing"

## Thank you for posting screenshots

![image](https://user-images.githubusercontent.com/46163555/181517253-b0cd09c4-649f-4512-80a9-083c46e74ae5.png)

Everyone likes seeing screenshots!  Thanks for putting them into your readme.

**Comment by iliabaranov** [comment]
Sure, I'll clarify the readme to mention this more explicitly, it's already in the requirements.txt :)
